name: RepairWrench
version: 1.0
main: Enes5519\RepairWrench\RepairWrench
api: 3.0.1
author: Enes5519

commands:
  repair:
    description: Shows the repair form
    usage: /repair
    permission: repairwrench.use
    overloads:
      default:

permissions:
  repairwrench.use:
    default: true